# -*- coding: utf-8 -*-
"""Principales communes françaises (> ~20 000 hab.) pour pages SEO locales."""

# (nom commune, code département)
COMMUNES = [
    ("Paris", "75"), ("Marseille", "13"), ("Lyon", "69"), ("Toulouse", "31"),
    ("Nice", "06"), ("Nantes", "44"), ("Montpellier", "34"), ("Strasbourg", "67"),
    ("Bordeaux", "33"), ("Lille", "59"), ("Rennes", "35"), ("Reims", "51"),
    ("Toulon", "83"), ("Saint-Étienne", "42"), ("Le Havre", "76"), ("Grenoble", "38"),
    ("Dijon", "21"), ("Angers", "49"), ("Nîmes", "30"), ("Villeurbanne", "69"),
    ("Clermont-Ferrand", "63"), ("Le Mans", "72"), ("Aix-en-Provence", "13"),
    ("Brest", "29"), ("Tours", "37"), ("Amiens", "80"), ("Limoges", "87"),
    ("Annecy", "74"), ("Perpignan", "66"), ("Boulogne-Billancourt", "92"),
    ("Metz", "57"), ("Besançon", "25"), ("Orléans", "45"), ("Saint-Denis", "93"),
    ("Argenteuil", "95"), ("Rouen", "76"), ("Montreuil", "93"), ("Mulhouse", "68"),
    ("Caen", "14"), ("Nancy", "54"), ("Roubaix", "59"), ("Tourcoing", "59"),
    ("Nanterre", "92"), ("Avignon", "84"), ("Vitry-sur-Seine", "94"),
    ("Créteil", "94"), ("Dunkerque", "59"), ("Poitiers", "86"),
    ("Asnières-sur-Seine", "92"), ("Courbevoie", "92"), ("Versailles", "78"),
    ("Colombes", "92"), ("Pau", "64"), ("Aubervilliers", "93"),
    ("Rueil-Malmaison", "92"), ("Champigny-sur-Marne", "94"), ("Antibes", "06"),
    ("Béziers", "34"), ("La Rochelle", "17"), ("Calais", "62"),
    ("Saint-Nazaire", "44"), ("Ajaccio", "2A"), ("Bourges", "18"),
    ("Colmar", "68"), ("Issy-les-Moulineaux", "92"), ("Noisy-le-Grand", "93"),
    ("Cergy", "95"), ("Vénissieux", "69"), ("Levallois-Perret", "92"),
    ("Quimper", "29"), ("Troyes", "10"), ("Neuilly-sur-Seine", "92"),
    ("Antony", "92"), ("Sarcelles", "95"), ("Lorient", "56"), ("Beauvais", "60"),
    ("Maisons-Alfort", "94"), ("Meaux", "77"), ("Hyères", "83"), ("Cholet", "49"),
    ("Fréjus", "83"), ("Villejuif", "94"), ("Alès", "30"), ("Massy", "91"),
    ("Pessac", "33"), ("Bayonne", "64"), ("Sète", "34"), ("Belfort", "90"),
    ("Évry-Courcouronnes", "91"), ("Cannes", "06"), ("Saint-Malo", "35"),
    ("Chambéry", "73"), ("Laval", "53"), ("Bastia", "2B"), ("Blois", "41"),
    ("Tarbes", "65"), ("Charleville-Mézières", "08"), ("Mérignac", "33"),
    ("Saint-Brieuc", "22"), ("Châteauroux", "36"), ("Roanne", "42"),
    ("Chartres", "28"), ("Montauban", "82"), ("Albi", "81"), ("Niort", "79"),
    ("Vannes", "56"), ("Agen", "47"), ("Périgueux", "24"), ("Angoulême", "16"),
    ("Valence", "26"), ("Carcassonne", "11"), ("Gap", "05"), ("Moulins", "03"),
    ("Nevers", "58"), ("Auxerre", "89"), ("Digne-les-Bains", "04"),
    ("Privas", "07"), ("Foix", "09"), ("Rodez", "12"), ("Aurillac", "15"),
    ("Guéret", "23"), ("Tulle", "19"), ("Mende", "48"), ("Cahors", "46"),
    ("Auch", "32"), ("Mont-de-Marsan", "40"), ("Pau", "64"), ("Biarritz", "64"),
    ("La Roche-sur-Yon", "85"), ("Saint-Lô", "50"), ("Alençon", "61"),
    ("Évreux", "27"), ("Beauvais", "60"), ("Laon", "02"), ("Arras", "62"),
    ("Lens", "62"), ("Valenciennes", "59"), ("Douai", "59"), ("Cambrai", "59"),
    ("Thionville", "57"), ("Épinal", "88"), ("Bar-le-Duc", "55"),
    ("Châlons-en-Champagne", "51"), ("Chaumont", "52"), ("Vesoul", "70"),
    ("Mâcon", "71"), ("Lons-le-Saunier", "39"), ("Melun", "77"),
    ("Meaux", "77"), ("Fontainebleau", "77"), ("Saint-Germain-en-Laye", "78"),
    ("Sartrouville", "78"), ("Poissy", "78"), ("Drancy", "93"), ("Bobigny", "93"),
    ("Pantin", "93"), ("Bondy", "93"), ("Saint-Ouen", "93"), ("Clichy", "92"),
    ("Le Blanc-Mesnil", "93"), ("Épinay-sur-Seine", "93"), ("Corbeil-Essonnes", "91"),
    ("Massy", "91"), ("Palaiseau", "91"), ("Suresnes", "92"), ("Clamart", "92"),
    ("Montrouge", "92"), ("Bagneux", "92"), ("Gennevilliers", "92"),
    ("Saint-Herblain", "44"), ("Rezé", "44"), ("Cholet", "49"), ("Saumur", "49"),
    ("La Roche-sur-Yon", "85"), ("Les Sables-d'Olonne", "85"), ("Lorient", "56"),
    ("Quimper", "29"), ("Brest", "29"), ("Morlaix", "29"), ("Vannes", "56"),
    ("Lannion", "22"), ("Dinan", "22"), ("Saint-Brieuc", "22"), ("Rennes", "35"),
    ("Fougères", "35"), ("Vitré", "35"), ("Redon", "35"), ("Laval", "53"),
    ("Mayenne", "53"), ("Le Mans", "72"), ("La Flèche", "72"), ("Alençon", "61"),
    ("Cherbourg-en-Octeville", "50"), ("Caen", "14"), ("Le Havre", "76"),
    ("Dieppe", "76"), ("Rouen", "76"), ("Évreux", "27"), ("Vernon", "27"),
    ("Chartres", "28"), ("Dreux", "28"), ("Orléans", "45"), ("Blois", "41"),
    ("Tours", "37"), ("Chinon", "37"), ("Poitiers", "86"), ("Châtellerault", "86"),
    ("Limoges", "87"), ("Brive-la-Gaillarde", "19"), ("Périgueux", "24"),
    ("Bergerac", "24"), ("Agen", "47"), ("Mont-de-Marsan", "40"), ("Dax", "40"),
    ("Pau", "64"), ("Bayonne", "64"), ("Biarritz", "64"), ("Angoulême", "16"),
    ("La Rochelle", "17"), ("Rochefort", "17"), ("Niort", "79"), ("Bordeaux", "33"),
    ("Mérignac", "33"), ("Pessac", "33"), ("Libourne", "33"), ("Toulouse", "31"),
    ("Montauban", "82"), ("Albi", "81"), ("Castres", "81"), ("Carcassonne", "11"),
    ("Narbonne", "11"), ("Béziers", "34"), ("Montpellier", "34"), ("Nîmes", "30"),
    ("Alès", "30"), ("Avignon", "84"), ("Orange", "84"), ("Carpentras", "84"),
    ("Marseille", "13"), ("Aix-en-Provence", "13"), ("Arles", "13"), ("Toulon", "83"),
    ("La Seyne-sur-Mer", "83"), ("Hyères", "83"), ("Nice", "06"), ("Cannes", "06"),
    ("Antibes", "06"), ("Grasse", "06"), ("Gap", "05"), ("Digne-les-Bains", "04"),
    ("Grenoble", "38"), ("Vienne", "38"), ("Valence", "26"), ("Romans-sur-Isère", "26"),
    ("Saint-Étienne", "42"), ("Roanne", "42"), ("Clermont-Ferrand", "63"),
    ("Vichy", "03"), ("Moulins", "03"), ("Montluçon", "03"), ("Le Puy-en-Velay", "43"),
    ("Saint-Étienne", "42"), ("Annecy", "74"), ("Annemasse", "74"), ("Chambéry", "73"),
    ("Albertville", "73"), ("Lyon", "69"), ("Villeurbanne", "69"), ("Vénissieux", "69"),
    ("Saint-Genis-Laval", "69"), ("Bourg-en-Bresse", "01"), ("Oyonnax", "01"),
    ("Dijon", "21"), ("Beaune", "21"), ("Besançon", "25"), ("Montbéliard", "25"),
    ("Belfort", "90"), ("Mulhouse", "68"), ("Colmar", "68"), ("Strasbourg", "67"),
    ("Haguenau", "67"), ("Metz", "57"), ("Thionville", "57"), ("Nancy", "54"),
    ("Lunéville", "54"), ("Reims", "51"), ("Châlons-en-Champagne", "51"),
    ("Troyes", "10"), ("Sens", "89"), ("Auxerre", "89"), ("Nevers", "58"),
    ("Lille", "59"), ("Roubaix", "59"), ("Tourcoing", "59"), ("Dunkerque", "59"),
    ("Calais", "62"), ("Boulogne-sur-Mer", "62"), ("Amiens", "80"), ("Abbeville", "80"),
    ("Beauvais", "60"), ("Compiègne", "60"), ("Creil", "60"), ("Ajaccio", "2A"),
    ("Porto-Vecchio", "2A"), ("Bastia", "2B"), ("Calvi", "2B"),
]

# Dédupliquer en gardant l'ordre
_seen = set()
COMMUNES_UNIQUE = []
for name, code in COMMUNES:
    key = (name.lower(), code)
    if key not in _seen:
        _seen.add(key)
        COMMUNES_UNIQUE.append((name, code))
